name: credit-risk-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - mlflow>=2.8.0
    - dagshub>=0.3.0
    - pandas>=2.0.0
    - numpy>=1.24.0
    - scikit-learn>=1.3.0
    - lightgbm>=4.0.0
    - xgboost>=2.0.0
    - shap>=0.43.0
    - optuna>=3.4.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - joblib>=1.3.0
    - pyyaml>=6.0.0
    - boto3>=1.28.0
